# Generated by Django 2.0.3 on 2019-04-30 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, verbose_name='Pozisyon')),
                ('name', models.CharField(max_length=50, verbose_name='İsim')),
                ('age', models.CharField(max_length=50, verbose_name='Yaş')),
                ('size', models.CharField(max_length=50, verbose_name='Boy')),
                ('weight', models.CharField(max_length=50, verbose_name='Kilo')),
                ('foot', models.CharField(max_length=50, verbose_name='Kullandığı Ayak')),
                ('club_history', models.CharField(max_length=50, verbose_name='Kulübe Katılma Tarihi')),
                ('hoca_gorüsü', models.TextField()),
                ('player_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekleyin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
