# Generated by Django 2.0.3 on 2019-05-04 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0003_database_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeri_category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('galeri_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('galeri_content', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf veya Video Ekleyin')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
