# Generated by Django 2.0.3 on 2019-05-04 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_duyuru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='duyuru_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='İçerik'),
        ),
    ]
