# Generated by Django 2.0.3 on 2019-05-04 14:39

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0007_auto_20190504_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haber_category', models.CharField(max_length=50, verbose_name='Kategori')),
                ('haber_title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('haber_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf veya Video Ekleyin')),
                ('haber_content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='duyuru_content',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='İçerik'),
            preserve_default=False,
        ),
    ]
