# Generated by Django 2.0.3 on 2019-05-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_puandurumu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puandurumu',
            name='galibiyet',
            field=models.CharField(max_length=50, verbose_name='Galibiyet'),
        ),
    ]
