# Generated by Django 2.0.3 on 2019-05-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20190505_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='duyuru_content',
            field=models.CharField(max_length=500, verbose_name='İçerik'),
        ),
    ]
