# Generated by Django 2.0.3 on 2019-05-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20190520_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='haber_content',
            field=models.CharField(max_length=25000, verbose_name='İçerik'),
        ),
    ]
