# Generated by Django 2.0.3 on 2019-05-20 00:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20190520_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haber',
            name='haber_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
