# Generated by Django 2.0.3 on 2019-05-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20190520_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puandurumu',
            options={'ordering': ['-pozisyon']},
        ),
    ]
