# Generated by Django 2.0.3 on 2019-05-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20190521_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puandurumu',
            options={'ordering': ['-puan']},
        ),
    ]
