# Generated by Django 2.0.3 on 2019-05-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20190521_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='database',
            options={'ordering': ['-age']},
        ),
    ]
